/*
 * The contents of this file are subject to the Mozilla Public
 * License Version 1.1 (the "License"); you may not use this file
 *  except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 * The Original Code is MozillaTranslator (Mozilla Localization Tool)
 *
 * The Initial Developer of the Original Code is Henrik Lynggaard Hansen
 *
 * Portions created by Henrik Lynggard Hansen are
 * Copyright (C) Henrik Lynggaard Hansen.
 * All Rights Reserved.
 *
 * Contributor(s):
 * Henrik Lynggaard Hansen (Initial Code)
 *
 */
package org.mozillatranslator.gui.dialog;

import org.mozillatranslator.kernel.Kernel;
import org.mozillatranslator.util.GuiTools;

/**
 *
 * @author  Henrik Lynggaard
 */
public class AboutDialog extends javax.swing.JDialog {

    /** Creates new form AboutDialog */
    public AboutDialog() {
        super(Kernel.mainWindow, "", true);
        initComponents();
        setTitle("MozillaTranslator " + Kernel.settings.getString("system.version", "(Unknown version)"));
        GuiTools.placeFrameAtCenter(this);
        System.gc();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JTabbedPane aboutTabbedPane = new javax.swing.JTabbedPane();
        javax.swing.JPanel generalPanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        productNameLabel = new javax.swing.JLabel();
        javax.swing.JTextArea generalArea = new javax.swing.JTextArea();
        versionNumberLabel = new javax.swing.JLabel();
        totalMemLabel = new javax.swing.JLabel();
        freeMemLabel = new javax.swing.JLabel();
        maxMemLabel = new javax.swing.JLabel();
        javax.swing.JPanel licencePanel = new javax.swing.JPanel();
        licenceArea = new javax.swing.JTextArea();
        javax.swing.JPanel addressPanel = new javax.swing.JPanel();
        adressArea = new javax.swing.JTextArea();
        okButtonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setTitle("About MozillaTranslator");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        generalPanel.setLayout(new java.awt.GridBagLayout());

        imageLabel.setBackground(new java.awt.Color(184, 207, 229));
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mozillatranslator/resource/mt_banner.gif"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        generalPanel.add(imageLabel, gridBagConstraints);

        productNameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        productNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productNameLabel.setText("MozillaTranslator");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 5);
        generalPanel.add(productNameLabel, gridBagConstraints);

        generalArea.setBackground(new java.awt.Color(184, 207, 229));
        generalArea.setColumns(15);
        generalArea.setEditable(false);
        generalArea.setRows(10);
        generalArea.setText("\nA localization tool for Mozilla and other XUL based programs\n\nOriginal code by:\nHenrik Lynggaard (Denmark)\n\nContributors in alphabetical order:\nTsahi Asher\nSerhiy Brytskyy\nRicardo Palomares");
        generalArea.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        generalPanel.add(generalArea, gridBagConstraints);

        versionNumberLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        versionNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        versionNumberLabel.setText("v" + Kernel.settings.getString(Kernel.settings.SYSTEM_VERSION));
        versionNumberLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        generalPanel.add(versionNumberLabel, gridBagConstraints);

        totalMemLabel.setText("Total memory: 123456 KB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        generalPanel.add(totalMemLabel, gridBagConstraints);

        freeMemLabel.setText("Free memory: 123456 KB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        generalPanel.add(freeMemLabel, gridBagConstraints);

        maxMemLabel.setText("Max memory: 123456 KB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        generalPanel.add(maxMemLabel, gridBagConstraints);

        aboutTabbedPane.addTab("General", null, generalPanel, "");

        licencePanel.setLayout(new java.awt.BorderLayout());

        licenceArea.setBackground(new java.awt.Color(184, 207, 229));
        licenceArea.setColumns(15);
        licenceArea.setEditable(false);
        licenceArea.setRows(12);
        licenceArea.setText("\nMozillaTranslator is released under MPL \nand PostCardWare\n\nMPL (Mozilla Public Licence 1.1)\nhttp://www.mozilla.org\n\nPostCardWare:\nIf you like this program,\nyou are encouraged to send a postcard\n(snail mail) to the author.\n\nLight bulb image taken from public domain clipart site\n(http://openclipart.org/media/files/Romanov/3529)");
        licenceArea.setOpaque(false);
        licencePanel.add(licenceArea, java.awt.BorderLayout.CENTER);

        aboutTabbedPane.addTab("Licence", null, licencePanel, "");

        addressPanel.setLayout(new java.awt.BorderLayout());

        adressArea.setBackground(new java.awt.Color(184, 207, 229));
        adressArea.setColumns(15);
        adressArea.setEditable(false);
        adressArea.setRows(12);
        adressArea.setText("\nPostcards should be sent to:\n\nHenrik Lynggaard\nBakkesvinget 22\nTulstrup\n3400 Hilleroed\nDenmark\n");
        adressArea.setOpaque(false);
        addressPanel.add(adressArea, java.awt.BorderLayout.CENTER);

        aboutTabbedPane.addTab("Address", null, addressPanel, "");

        getContentPane().add(aboutTabbedPane, java.awt.BorderLayout.NORTH);

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(60, 29));
        okButton.setMinimumSize(new java.awt.Dimension(60, 29));
        okButton.setPreferredSize(new java.awt.Dimension(60, 29));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        okButtonPanel.add(okButton);

        getContentPane().add(okButtonPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        maxMemLabel.setText("Max. memory: " + (Runtime.getRuntime().maxMemory() / 1024) + " KB");
        totalMemLabel.setText("Total memory: " + (Runtime.getRuntime().totalMemory() / 1024) + " KB");
        freeMemLabel.setText("Free memory: " + (Runtime.getRuntime().freeMemory() / 1024) + " KB");
    }//GEN-LAST:event_formWindowOpened

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea adressArea;
    private javax.swing.JLabel freeMemLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextArea licenceArea;
    private javax.swing.JLabel maxMemLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel okButtonPanel;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel totalMemLabel;
    private javax.swing.JLabel versionNumberLabel;
    // End of variables declaration//GEN-END:variables
}
