/*
 * The contents of this file are subject to the Mozilla Public
 * License Version 1.1 (the "License"); you may not use this file
 *  except in compliance with the License. You may obtain a copy of
 * the License at http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS
 * IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * rights and limitations under the License.
 *
 * The Original Code is MozillaTranslator (Mozilla Localization Tool)
 *
 * The Initial Developer of the Original Code is Henrik Lynggaard Hansen
 *
 * Portions created by Henrik Lynggard Hansen are
 * Copyright (C) Henrik Lynggaard Hansen.
 * All Rights Reserved.
 *
 * Contributor(s):
 * Henrik Lynggaard Hansen (Initial Code)
 *
 */


package org.mozillatranslator.gui.dialog;

import java.io.*;
import javax.swing.*;
import org.mozillatranslator.datamodel.*;
import org.mozillatranslator.kernel.*;
import org.mozillatranslator.util.*;

/**
 *
 * @author  Henrik Lynggaard
 */
public class EditCustomFileDialog extends javax.swing.JDialog
{
    
    private GenericFile custom;
    /** Creates new form EditCustomFile */
    public EditCustomFileDialog(GenericFile cfile)
    {
        super(Kernel.mainWindow,"Edit custom file", true);
        custom = cfile;
        initComponents();
        JDialogHelper.setupOKCancelHotkeys(this, okButton, cancelButton);
        GuiTools.placeFrameAtCenter(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        realLabel = new javax.swing.JLabel();
        realField = new javax.swing.JTextField();
        realButton = new javax.swing.JButton();
        relativeLabel = new javax.swing.JLabel();
        relativeField = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Dialog", 0, 12));
        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(72, 25));
        okButton.setMinimumSize(new java.awt.Dimension(72, 25));
        okButton.setPreferredSize(new java.awt.Dimension(72, 25));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonPressed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setFont(new java.awt.Font("Dialog", 0, 12));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonPressed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        infoPanel.setLayout(new java.awt.GridBagLayout());

        nameLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nameLabel.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        infoPanel.add(nameLabel, gridBagConstraints);

        nameField.setColumns(30);
        nameField.setText("filler");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        infoPanel.add(nameField, gridBagConstraints);

        realLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        realLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        realLabel.setText("Original file");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        infoPanel.add(realLabel, gridBagConstraints);

        realField.setColumns(30);
        realField.setText("filler");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        infoPanel.add(realField, gridBagConstraints);

        realButton.setFont(new java.awt.Font("Dialog", 0, 12));
        realButton.setMnemonic('C');
        realButton.setText("Choose");
        realButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realButtonPressed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        infoPanel.add(realButton, gridBagConstraints);

        relativeLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        relativeLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        relativeLabel.setText("Mount point");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        infoPanel.add(relativeLabel, gridBagConstraints);

        relativeField.setColumns(30);
        relativeField.setText("filler");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        infoPanel.add(relativeField, gridBagConstraints);

        getContentPane().add(infoPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cancelButtonPressed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonPressed
    {//GEN-HEADEREND:event_cancelButtonPressed
        okay = false;
        setVisible(false);
    }//GEN-LAST:event_cancelButtonPressed
    
    private void okButtonPressed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonPressed
    {//GEN-HEADEREND:event_okButtonPressed
        okay = true;
        setVisible(false);
    }//GEN-LAST:event_okButtonPressed
    
    private void realButtonPressed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_realButtonPressed
    {//GEN-HEADEREND:event_realButtonPressed
        File defaultFile;
        JFileChooser chooser;
        int result;
        
        defaultFile = new File(realField.getText());
        File f = defaultFile.isFile() ? defaultFile :
            new File(Kernel.settings.getString(Settings.GUI_IMPORT_FILE_CHOOSER_PATH));
            chooser = new JFileChooser(f);
            
            chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            chooser.setDialogTitle("Select original file ");
            chooser.setSelectedFile(defaultFile);
            
            result = chooser.showDialog(this,"Choose");
            if (result == JFileChooser.APPROVE_OPTION)
            {
                Kernel.settings.setString(Settings.GUI_IMPORT_FILE_CHOOSER_PATH,
                chooser.getCurrentDirectory().getAbsolutePath());
                defaultFile = chooser.getSelectedFile();
                realField.setText(defaultFile.toString());
            }
            
    }//GEN-LAST:event_realButtonPressed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        okay = false;
        setVisible(false);
        
    }//GEN-LAST:event_closeDialog
    
    public boolean showDialog()
    {
        okay = false;
        nameField.setText(custom.getName());
        realField.setText(custom.getRealFilename());
        relativeField.setText(custom.getRelativeFilename());
        setVisible(true);
        
        if (okay)
        {
            custom.setName(nameField.getText());
            custom.setRealFilename(realField.getText());
            custom.setRelativeFilename(relativeField.getText());
        }
        dispose();
        return okay;
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton realButton;
    private javax.swing.JTextField realField;
    private javax.swing.JLabel realLabel;
    private javax.swing.JTextField relativeField;
    private javax.swing.JLabel relativeLabel;
    // End of variables declaration//GEN-END:variables
    private boolean okay;
}
