/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MassChangePanel.java
 *
 * Created on 05-ene-2012, 14:14:51
 */

package org.mozillatranslator.gui.dialog;

import java.awt.Container;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.mozillatranslator.action.ChangeUnit;
import org.mozillatranslator.action.FieldToChange;
import org.mozillatranslator.datamodel.TrnsStatus;
import org.mozillatranslator.kernel.Kernel;

/**
 *
 * @author rpalomares
 */
public class MassChangePanel extends javax.swing.JPanel {
    private boolean okPressed;

    /** Creates new form MassChangePanel */
    public MassChangePanel() {
        initComponents();
        for(TrnsStatus ts : TrnsStatus.values()) {
            trnsStatusCombo.addItem(ts);
        }
    }

    /**
     * Returns OK if the user has chosen OK
     * @return true if the user has chosen OK
     */
    public boolean isOkPressed() {
        return okPressed;
    }

    public List<ChangeUnit> getChangesToDo() {
        ArrayList<ChangeUnit> result = new ArrayList<ChangeUnit>();

        if (this.keepOrigCheckBox.isSelected()) {
            result.add(new ChangeUnit(FieldToChange.KEEPORIG,
                    this.isKeepOriginalValue() ? "true" : "false"));
        }

        if (this.fuzzyCheckBox.isSelected()) {
            result.add(new ChangeUnit(FieldToChange.FUZZY,
                    this.isFuzzyValue() ? "true" : "false"));
        }

        if (this.translationCheckBox.isSelected()) {
            result.add(new ChangeUnit(FieldToChange.TRANSLATION,
                    this.getTranslationValue()));
        }

        if (this.commentCheckBox.isSelected()) {
            result.add(new ChangeUnit(FieldToChange.COMMENT,
                    this.getCommentValue()));
        }

        if (this.trnsStatusCheckBox.isSelected()) {
            result.add(new ChangeUnit(FieldToChange.TRNSSTATUS,
                    this.getTrnsStatusValue().toString()));
        }
        return result;
    }

    public boolean isKeepOriginalValue() {
        return this.keepOrigSetRButton.isSelected();
    }

    public boolean isFuzzyValue() {
        return this.fuzzySetRButton.isSelected();
    }

    public String getTranslationValue() {
        return this.translatedTexTField.getText();
    }

    public String getCommentValue() {
        return this.commentTextField.getText();
    }

    public TrnsStatus getTrnsStatusValue() {
        return (TrnsStatus) this.trnsStatusCombo.getSelectedItem();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        keepOrigBGroup = new javax.swing.ButtonGroup();
        fuzzyBGroup = new javax.swing.ButtonGroup();
        chooseChangesLabel = new javax.swing.JLabel();
        keepOrigCheckBox = new javax.swing.JCheckBox();
        fuzzyCheckBox = new javax.swing.JCheckBox();
        translationCheckBox = new javax.swing.JCheckBox();
        commentCheckBox = new javax.swing.JCheckBox();
        trnsStatusCheckBox = new javax.swing.JCheckBox();
        trnsStatusCombo = new javax.swing.JComboBox();
        commentTextField = new javax.swing.JTextField();
        translatedTexTField = new javax.swing.JTextField();
        fuzzySetRButton = new javax.swing.JRadioButton();
        fuzzyClearRButton = new javax.swing.JRadioButton();
        keepOrigSetRButton = new javax.swing.JRadioButton();
        keepOrigClearRButton = new javax.swing.JRadioButton();
        okCancelPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        chooseChangesLabel.setText("Choose changes to apply");

        keepOrigCheckBox.setMnemonic('K');
        keepOrigCheckBox.setText("Keep Original flag");
        keepOrigCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                keepOrigCheckBoxItemStateChanged(evt);
            }
        });

        fuzzyCheckBox.setMnemonic('F');
        fuzzyCheckBox.setText("Fuzzy flag");
        fuzzyCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fuzzyCheckBoxItemStateChanged(evt);
            }
        });

        translationCheckBox.setMnemonic('T');
        translationCheckBox.setText("Translated value");
        translationCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                translationCheckBoxItemStateChanged(evt);
            }
        });

        commentCheckBox.setMnemonic('C');
        commentCheckBox.setText("Comment value");
        commentCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                commentCheckBoxItemStateChanged(evt);
            }
        });

        trnsStatusCheckBox.setMnemonic('r');
        trnsStatusCheckBox.setText("Translation Status");
        trnsStatusCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                trnsStatusCheckBoxItemStateChanged(evt);
            }
        });

        trnsStatusCombo.setEnabled(false);

        commentTextField.setEnabled(false);

        translatedTexTField.setEnabled(false);

        fuzzyBGroup.add(fuzzySetRButton);
        fuzzySetRButton.setMnemonic('e');
        fuzzySetRButton.setText("Set");
        fuzzySetRButton.setEnabled(false);

        fuzzyBGroup.add(fuzzyClearRButton);
        fuzzyClearRButton.setMnemonic('a');
        fuzzyClearRButton.setText("Clear");
        fuzzyClearRButton.setEnabled(false);

        keepOrigBGroup.add(keepOrigSetRButton);
        keepOrigSetRButton.setMnemonic('S');
        keepOrigSetRButton.setText("Set");
        keepOrigSetRButton.setEnabled(false);

        keepOrigBGroup.add(keepOrigClearRButton);
        keepOrigClearRButton.setMnemonic('l');
        keepOrigClearRButton.setText("Clear");
        keepOrigClearRButton.setEnabled(false);

        okCancelPanel.setLayout(new java.awt.GridBagLayout());

        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(76, 31));
        okButton.setMinimumSize(new java.awt.Dimension(76, 31));
        okButton.setPreferredSize(new java.awt.Dimension(76, 31));
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        okCancelPanel.add(okButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.setMaximumSize(new java.awt.Dimension(76, 31));
        cancelButton.setMinimumSize(new java.awt.Dimension(76, 31));
        cancelButton.setPreferredSize(new java.awt.Dimension(76, 31));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        okCancelPanel.add(cancelButton, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okCancelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addComponent(chooseChangesLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trnsStatusCheckBox)
                            .addComponent(commentCheckBox)
                            .addComponent(translationCheckBox)
                            .addComponent(fuzzyCheckBox)
                            .addComponent(keepOrigCheckBox))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(commentTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(trnsStatusCombo, 0, 146, Short.MAX_VALUE)
                            .addComponent(translatedTexTField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(keepOrigSetRButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(keepOrigClearRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(fuzzySetRButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fuzzyClearRButton))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseChangesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keepOrigCheckBox)
                    .addComponent(keepOrigSetRButton)
                    .addComponent(keepOrigClearRButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuzzyCheckBox)
                    .addComponent(fuzzySetRButton)
                    .addComponent(fuzzyClearRButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(translationCheckBox)
                    .addComponent(translatedTexTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commentCheckBox)
                    .addComponent(commentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trnsStatusCheckBox)
                    .addComponent(trnsStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okCancelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void keepOrigCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_keepOrigCheckBoxItemStateChanged
        this.keepOrigSetRButton.setEnabled(evt.getStateChange() == ItemEvent.SELECTED);
        this.keepOrigClearRButton.setEnabled(evt.getStateChange() == ItemEvent.SELECTED);
        this.keepOrigSetRButton.grabFocus();
    }//GEN-LAST:event_keepOrigCheckBoxItemStateChanged

    private void fuzzyCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fuzzyCheckBoxItemStateChanged
        this.fuzzySetRButton.setEnabled(evt.getStateChange() == ItemEvent.SELECTED);
        this.fuzzyClearRButton.setEnabled(evt.getStateChange() == ItemEvent.SELECTED);
        this.fuzzySetRButton.grabFocus();
    }//GEN-LAST:event_fuzzyCheckBoxItemStateChanged

    private void translationCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_translationCheckBoxItemStateChanged
        this.translatedTexTField.setEnabled(evt.getStateChange() == ItemEvent.SELECTED);
        this.translatedTexTField.grabFocus();
    }//GEN-LAST:event_translationCheckBoxItemStateChanged

    private void commentCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_commentCheckBoxItemStateChanged
        this.commentTextField.setEnabled(evt.getStateChange() == ItemEvent.SELECTED);
        this.commentTextField.grabFocus();
    }//GEN-LAST:event_commentCheckBoxItemStateChanged

    private void trnsStatusCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_trnsStatusCheckBoxItemStateChanged
        this.trnsStatusCombo.setEnabled(evt.getStateChange() == ItemEvent.SELECTED);
        this.trnsStatusCombo.grabFocus();
    }//GEN-LAST:event_trnsStatusCheckBoxItemStateChanged

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (JOptionPane.showConfirmDialog(Kernel.mainWindow,
                "Are you sure to apply these changes?",
                "Confirm applying changes",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            okPressed = true;
            Container c = this.getTopLevelAncestor();
            c.setVisible(false);
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        okPressed = false;
        Container c = this.getTopLevelAncestor();
        c.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel chooseChangesLabel;
    private javax.swing.JCheckBox commentCheckBox;
    private javax.swing.JTextField commentTextField;
    private javax.swing.ButtonGroup fuzzyBGroup;
    private javax.swing.JCheckBox fuzzyCheckBox;
    private javax.swing.JRadioButton fuzzyClearRButton;
    private javax.swing.JRadioButton fuzzySetRButton;
    private javax.swing.ButtonGroup keepOrigBGroup;
    private javax.swing.JCheckBox keepOrigCheckBox;
    private javax.swing.JRadioButton keepOrigClearRButton;
    private javax.swing.JRadioButton keepOrigSetRButton;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel okCancelPanel;
    private javax.swing.JTextField translatedTexTField;
    private javax.swing.JCheckBox translationCheckBox;
    private javax.swing.JCheckBox trnsStatusCheckBox;
    private javax.swing.JComboBox trnsStatusCombo;
    // End of variables declaration//GEN-END:variables

}
